[tool.poetry]
name = "jamstack-api"
version = "0.1.0"
description = "Webhook endpoints to optimize your JAMStack static site."
authors = ["Todd Birchard <toddbirchard@gmail.com>"]
maintainers = ["Todd Birchard <toddbirchard@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/toddbirchard/jamstack-api/"
repository = "https://github.com/toddbirchard/jamstack-api/"
documentation = "https://github.com/toddbirchard/jamstack-api/blob/master/README.md"
keywords = [
  "API",
  "Rest API",
  "Automation",
  "FastAPI",
  "Webhooks"
]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "*"
pydantic = "*"
pandas = "*"
sqlalchemy = "*"
pymysql = "*"
requests = "*"
google-cloud = "*"
google-cloud-storage = "*"
google-cloud-bigquery = "*"
google-cloud-bigquery-storage = "*"
pillow = "*"
python-resize-image = "*"
webp-converter = "*"
python-dotenv = "*"
pyjwt = ">=2.0"
mixpanel = "*"
loguru = "*"
twilio = "*"
beautifulsoup4 = "*"
boto = "*"
botocore = "*"
uvicorn = "*"
PyGithub = "*"
ddtrace = "*"
pyarrow = "^6.0.0"
extraction = "*"
metadata-parser = "*"
fastapi-mail = "*"
google-auth = "^2.6.6"

[tool.poetry.dev-dependencies]
pytest = "*"
coverage = "*"
mock = "*"
mypy = "*"
black = "*"
isort = "*"
flake8 = "*"
pylint = "*"

[tool.poetry.scripts]
run = "asgi:app"

[tool.poetry.urls]
issues = "https://github.com/toddbirchard/jamstack-api/issues"

[build-system]
requires = ["poetry>=1.1.12"]
build-backend = "poetry.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
disable="C0103,C0301,W0703,W0621"