[tool.poetry]
name = "api"
version = "0.1.0"
description = "Webhook endpoints to optimize your JAMStack static site."
authors = ["Todd Birchard <toddbirchard@gmail.com>"]
maintainers = ["Todd Birchard <toddbirchard@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/toddbirchard/jamstack-api/"
repository = "https://github.com/toddbirchard/jamstack-api/"
documentation = "https://github.com/toddbirchard/jamstack-api/"
keywords = [
  "API",
  "JAMStack",
  "Automation",
  "Ghost",
  "Webhooks"
]

[tool.poetry.dependencies]
python = "^3.8"
flask = "*"
pandas = "*"
sqlalchemy = "*"
pymysql = "*"
requests = "*"
google-cloud-storage = "*"
google-cloud-bigquery = "*"
google-cloud-bigquery-storage = "*"
pillow = "*"
python-resize-image = "*"
webp-converter = "*"
python-dotenv = "*"
pyjwt="*"
mixpanel = "*"
loguru = "*"
twilio = "*"
beautifulsoup4 = "*"
extruct = "*"
flask-cors = "*"
simplejson = "*"
ddtrace = "*"
boto = "*"
botocore = "*"
uwsgi = "*"
pyarrow = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest-flask = "*"
mock = "*"
mypy = "*"
black = "^20.8b1"
isort = "^5.6.4"

[tool.poetry.scripts]
run = "wsgi:api"

[tool.poetry.urls]
issues = "https://github.com/toddbirchard/jamstack-api/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
