[tool.poetry]
name = "api"
version = "0.1.0"
description = "Webhook endpoints to optimize your JAMStack static site."
authors = ["Todd Birchard <toddbirchard@gmail.com>"]
maintainers = ["Todd Birchard <toddbirchard@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/hackersandslackers/jamstack-automations/"
repository = "https://github.com/hackersandslackers/jamstack-automations/"
documentation = "https://hackersandslackers.com/jamstack-automations/"
keywords = [
  "API",
  "JAMStack",
  "Automation",
  "Optimization",
  "Flask"
]

[tool.poetry.dependencies]
python = "^3.8"
flask = "*"
pandas = "*"
sqlalchemy = "*"
pymysql = "*"
requests = "*"
google-cloud-storage = "*"
google-cloud-bigquery = "*"
google-cloud-bigquery-storage = "*"
pillow = "*"
python-resize-image = "*"
webp-converter = "*"
python-dotenv = "*"
pyjwt="*"
pybigquery = "*"
mixpanel = "*"
loguru = "*"
twilio = "*"
beautifulsoup4 = "*"
extruct = "*"
simplejson = "*"
uwsgi = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
mock = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
run = "wsgi:api"

[tool.poetry.urls]
issues = "https://github.com/hackersandslackers/jamstack-automations/issues"